package com.oms.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LineitemTarget generated by hbm2java
 */
@Entity
@Table(name = "lineitem_target", uniqueConstraints = @UniqueConstraint(columnNames = "TARGET_TYPE"))
public class LineitemTarget implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2342954575310800425L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LINEITEM_TARGET_ID", unique = true, nullable = false)
	private long id;
	@JsonBackReference
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "LINEITEM_ID", referencedColumnName = "LINE_ITEM_ID", insertable = false, updatable = false)
	private LineItems lineItems;
	
	
    @OneToMany(fetch=FetchType.EAGER)
	@JoinTable(name = "lineitem_target_audience_target_values", joinColumns = { @JoinColumn(name = "LINEITEM_TARGET_ID") }, inverseJoinColumns = {
			@JoinColumn(name = "audience_target_values_id") })
	private Set<AudienceTargetValues> audienceTargetValues;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "TARGET_TYPE", unique = true)
	private AudienceTargetType audienceTargetType;

	@JsonIgnore
	@Column(name="deleted", columnDefinition = "BIT")
	private boolean deleted=false;

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public LineItems getLineItems() {
		return this.lineItems;
	}

	public void setLineItems(LineItems lineItems) {
		this.lineItems = lineItems;
	}

	

	
	public Set<AudienceTargetValues> getAudienceTargetValues() {
		return audienceTargetValues;
	}

	public void setAudienceTargetValues(Set<AudienceTargetValues> audienceTargetValues) {
		this.audienceTargetValues = audienceTargetValues;
	}

	public AudienceTargetType getAudienceTargetType() {
		return this.audienceTargetType;
	}

	public void setAudienceTargetType(AudienceTargetType audienceTargetType) {
		this.audienceTargetType = audienceTargetType;
	}

}
