package com.oms.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AudienceTargetValues generated by hbm2java
 */
@Entity
@Table(name = "ORDER_AUDIENCE_TARGET_VALUES")
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderAudienceTargetValues implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4814591305441703642L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	@Column(name = "VALUE", length = 45)
	private String value;
	@Column(name = "STATUS", nullable = false)
	private boolean status;
	
/*	@Column(name = "ORDER_LINE_ITEM_TARGET_ID", nullable = false)
	private Long orderTargetId;

	public Long getOrderTargetId() {
		return orderTargetId;
	}

	public void setOrderTargetId(Long orderTargetId) {
		this.orderTargetId = orderTargetId;
	}*/

	public OrderAudienceTargetValues() {
	}

	public OrderAudienceTargetValues(boolean status) {
		this.status = status;
	}

	public OrderAudienceTargetValues(String value, boolean status) {

		this.value = value;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	
}
