package com.oms.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RateCardAdUnitId generated by hbm2java
 */
@Embeddable
public class RateCardAdUnitId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8230483667717637389L;
	private Long rateCardId;
	private Long adUnitId;

	public RateCardAdUnitId() {
	}

	public RateCardAdUnitId(Long rateCardId, Long adUnitId) {
		this.rateCardId = rateCardId;
		this.adUnitId = adUnitId;
	}

	@Column(name = "RATE_CARD_ID")
	public Long getRateCardId() {
		return this.rateCardId;
	}

	public void setRateCardId(Long rateCardId) {
		this.rateCardId = rateCardId;
	}

	@Column(name = "AD_UNIT_ID")
	public Long getAdUnitId() {
		return this.adUnitId;
	}

	public void setAdUnitId(Long adUnitId) {
		this.adUnitId = adUnitId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RateCardAdUnitId))
			return false;
		RateCardAdUnitId castOther = (RateCardAdUnitId) other;

		return ((this.getRateCardId() == castOther.getRateCardId()) || (this
				.getRateCardId() != null && castOther.getRateCardId() != null && this
				.getRateCardId().equals(castOther.getRateCardId())))
				&& ((this.getAdUnitId() == castOther.getAdUnitId()) || (this
						.getAdUnitId() != null
						&& castOther.getAdUnitId() != null && this
						.getAdUnitId().equals(castOther.getAdUnitId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRateCardId() == null ? 0 : this.getRateCardId()
						.hashCode());
		result = 37 * result
				+ (getAdUnitId() == null ? 0 : this.getAdUnitId().hashCode());
		return result;
	}

}
